export type Country = {
  name: { common: string }
  cca2: string
}

export const WORLD_COUNTRIES: Country[] = [
  { cca2: "AF", name: { common: "Afghanistan" } },
  { cca2: "AX", name: { common: "Åland Islands" } },
  { cca2: "AL", name: { common: "Albania" } },
  { cca2: "DZ", name: { common: "Algeria" } },
  { cca2: "AS", name: { common: "American Samoa" } },
  { cca2: "AD", name: { common: "Andorra" } },
  { cca2: "AO", name: { common: "Angola" } },
  { cca2: "AI", name: { common: "Anguilla" } },
  { cca2: "AQ", name: { common: "Antarctica" } },
  { cca2: "AG", name: { common: "Antigua and Barbuda" } },
  { cca2: "AR", name: { common: "Argentina" } },
  { cca2: "AM", name: { common: "Armenia" } },
  { cca2: "AW", name: { common: "Aruba" } },
  { cca2: "AU", name: { common: "Australia" } },
  { cca2: "AT", name: { common: "Austria" } },
  { cca2: "AZ", name: { common: "Azerbaijan" } },
  { cca2: "BS", name: { common: "Bahamas" } },
  { cca2: "BH", name: { common: "Bahrain" } },
  { cca2: "BD", name: { common: "Bangladesh" } },
  { cca2: "BB", name: { common: "Barbados" } },
  { cca2: "BY", name: { common: "Belarus" } },
  { cca2: "BE", name: { common: "Belgium" } },
  { cca2: "BZ", name: { common: "Belize" } },
  { cca2: "BJ", name: { common: "Benin" } },
  { cca2: "BM", name: { common: "Bermuda" } },
  { cca2: "BT", name: { common: "Bhutan" } },
  { cca2: "BO", name: { common: "Bolivia" } },
  { cca2: "BA", name: { common: "Bosnia and Herzegovina" } },
  { cca2: "BW", name: { common: "Botswana" } },
  { cca2: "BR", name: { common: "Brazil" } },
  { cca2: "BN", name: { common: "Brunei" } },
  { cca2: "BG", name: { common: "Bulgaria" } },
  { cca2: "BF", name: { common: "Burkina Faso" } },
  { cca2: "BI", name: { common: "Burundi" } },
  { cca2: "KH", name: { common: "Cambodia" } },
  { cca2: "CM", name: { common: "Cameroon" } },
  { cca2: "CA", name: { common: "Canada" } },
  { cca2: "CV", name: { common: "Cape Verde" } },
  { cca2: "KY", name: { common: "Cayman Islands" } },
  { cca2: "CF", name: { common: "Central African Republic" } },
  { cca2: "TD", name: { common: "Chad" } },
  { cca2: "CL", name: { common: "Chile" } },
  { cca2: "CN", name: { common: "China" } },
  { cca2: "CO", name: { common: "Colombia" } },
  { cca2: "KM", name: { common: "Comoros" } },
  { cca2: "CG", name: { common: "Congo" } },
  { cca2: "CD", name: { common: "Congo (Democratic Republic)" } },
  { cca2: "CK", name: { common: "Cook Islands" } },
  { cca2: "CR", name: { common: "Costa Rica" } },
  { cca2: "HR", name: { common: "Croatia" } },
  { cca2: "CU", name: { common: "Cuba" } },
  { cca2: "CY", name: { common: "Cyprus" } },
  { cca2: "CZ", name: { common: "Czechia" } },
  { cca2: "DK", name: { common: "Denmark" } },
  { cca2: "DJ", name: { common: "Djibouti" } },
  { cca2: "DM", name: { common: "Dominica" } },
  { cca2: "DO", name: { common: "Dominican Republic" } },
  { cca2: "EC", name: { common: "Ecuador" } },
  { cca2: "EG", name: { common: "Egypt" } },
  { cca2: "SV", name: { common: "El Salvador" } },
  { cca2: "GQ", name: { common: "Equatorial Guinea" } },
  { cca2: "ER", name: { common: "Eritrea" } },
  { cca2: "EE", name: { common: "Estonia" } },
  { cca2: "SZ", name: { common: "Eswatini" } },
  { cca2: "ET", name: { common: "Ethiopia" } },
  { cca2: "FJ", name: { common: "Fiji" } },
  { cca2: "FI", name: { common: "Finland" } },
  { cca2: "FR", name: { common: "France" } },
  { cca2: "GA", name: { common: "Gabon" } },
  { cca2: "GM", name: { common: "Gambia" } },
  { cca2: "GE", name: { common: "Georgia" } },
  { cca2: "DE", name: { common: "Germany" } },
  { cca2: "GH", name: { common: "Ghana" } },
  { cca2: "GR", name: { common: "Greece" } },
  { cca2: "GD", name: { common: "Grenada" } },
  { cca2: "GT", name: { common: "Guatemala" } },
  { cca2: "GN", name: { common: "Guinea" } },
  { cca2: "GW", name: { common: "Guinea-Bissau" } },
  { cca2: "GY", name: { common: "Guyana" } },
  { cca2: "HT", name: { common: "Haiti" } },
  { cca2: "HN", name: { common: "Honduras" } },
  { cca2: "HK", name: { common: "Hong Kong" } },
  { cca2: "HU", name: { common: "Hungary" } },
  { cca2: "IS", name: { common: "Iceland" } },
  { cca2: "IN", name: { common: "India" } },
  { cca2: "ID", name: { common: "Indonesia" } },
  { cca2: "IR", name: { common: "Iran" } },
  { cca2: "IQ", name: { common: "Iraq" } },
  { cca2: "IE", name: { common: "Ireland" } },
  { cca2: "IL", name: { common: "Israel" } },
  { cca2: "IT", name: { common: "Italy" } },
  { cca2: "JM", name: { common: "Jamaica" } },
  { cca2: "JP", name: { common: "Japan" } },
  { cca2: "JO", name: { common: "Jordan" } },
  { cca2: "KZ", name: { common: "Kazakhstan" } },
  { cca2: "KE", name: { common: "Kenya" } },
  { cca2: "KR", name: { common: "Korea (South)" } },
  { cca2: "KW", name: { common: "Kuwait" } },
  { cca2: "KG", name: { common: "Kyrgyzstan" } },
  { cca2: "LA", name: { common: "Laos" } },
  { cca2: "LV", name: { common: "Latvia" } },
  { cca2: "LB", name: { common: "Lebanon" } },
  { cca2: "LS", name: { common: "Lesotho" } },
  { cca2: "LR", name: { common: "Liberia" } },
  { cca2: "LY", name: { common: "Libya" } },
  { cca2: "LI", name: { common: "Liechtenstein" } },
  { cca2: "LT", name: { common: "Lithuania" } },
  { cca2: "LU", name: { common: "Luxembourg" } },
  { cca2: "MO", name: { common: "Macao" } },
  { cca2: "MG", name: { common: "Madagascar" } },
  { cca2: "MW", name: { common: "Malawi" } },
  { cca2: "MY", name: { common: "Malaysia" } },
  { cca2: "MV", name: { common: "Maldives" } },
  { cca2: "ML", name: { common: "Mali" } },
  { cca2: "MT", name: { common: "Malta" } },
  { cca2: "MX", name: { common: "Mexico" } },
  { cca2: "MD", name: { common: "Moldova" } },
  { cca2: "MC", name: { common: "Monaco" } },
  { cca2: "MN", name: { common: "Mongolia" } },
  { cca2: "ME", name: { common: "Montenegro" } },
  { cca2: "MA", name: { common: "Morocco" } },
  { cca2: "MZ", name: { common: "Mozambique" } },
  { cca2: "MM", name: { common: "Myanmar" } },
  { cca2: "NA", name: { common: "Namibia" } },
  { cca2: "NP", name: { common: "Nepal" } },
  { cca2: "NL", name: { common: "Netherlands" } },
  { cca2: "NZ", name: { common: "New Zealand" } },
  { cca2: "NI", name: { common: "Nicaragua" } },
  { cca2: "NE", name: { common: "Niger" } },
  { cca2: "NG", name: { common: "Nigeria" } },
  { cca2: "NO", name: { common: "Norway" } },
  { cca2: "OM", name: { common: "Oman" } },
  { cca2: "PK", name: { common: "Pakistan" } },
  { cca2: "PS", name: { common: "Palestine" } },
  { cca2: "PA", name: { common: "Panama" } },
  { cca2: "PG", name: { common: "Papua New Guinea" } },
  { cca2: "PY", name: { common: "Paraguay" } },
  { cca2: "PE", name: { common: "Peru" } },
  { cca2: "PH", name: { common: "Philippines" } },
  { cca2: "PL", name: { common: "Poland" } },
  { cca2: "PT", name: { common: "Portugal" } },
  { cca2: "QA", name: { common: "Qatar" } },
  { cca2: "RO", name: { common: "Romania" } },
  { cca2: "RU", name: { common: "Russia" } },
  { cca2: "RW", name: { common: "Rwanda" } },
  { cca2: "SA", name: { common: "Saudi Arabia" } },
  { cca2: "SN", name: { common: "Senegal" } },
  { cca2: "RS", name: { common: "Serbia" } },
  { cca2: "SG", name: { common: "Singapore" } },
  { cca2: "SK", name: { common: "Slovakia" } },
  { cca2: "SI", name: { common: "Slovenia" } },
  { cca2: "SO", name: { common: "Somalia" } },
  { cca2: "ZA", name: { common: "South Africa" } },
  { cca2: "ES", name: { common: "Spain" } },
  { cca2: "LK", name: { common: "Sri Lanka" } },
  { cca2: "SD", name: { common: "Sudan" } },
  { cca2: "SE", name: { common: "Sweden" } },
  { cca2: "CH", name: { common: "Switzerland" } },
  { cca2: "TW", name: { common: "Taiwan" } },
  { cca2: "TZ", name: { common: "Tanzania" } },
  { cca2: "TH", name: { common: "Thailand" } },
  { cca2: "TN", name: { common: "Tunisia" } },
  { cca2: "TR", name: { common: "Turkey" } },
  { cca2: "UG", name: { common: "Uganda" } },
  { cca2: "UA", name: { common: "Ukraine" } },
  { cca2: "AE", name: { common: "United Arab Emirates" } },
  { cca2: "GB", name: { common: "United Kingdom" } },
  { cca2: "US", name: { common: "United States" } },
  { cca2: "UY", name: { common: "Uruguay" } },
  { cca2: "UZ", name: { common: "Uzbekistan" } },
  { cca2: "VE", name: { common: "Venezuela" } },
  { cca2: "VN", name: { common: "Vietnam" } },
  { cca2: "YE", name: { common: "Yemen" } },
  { cca2: "ZM", name: { common: "Zambia" } },
  { cca2: "ZW", name: { common: "Zimbabwe" } }
]
