export interface ZoneDefinition {
  zone: string
  regions: string[]
}

export const LOCATION_ZONES: ZoneDefinition[] = [
  {
    zone: "ZONE 1",
    regions: [
      "NO 2 RIVER",
      "BAW BAW",
      "FREEMAN STREET",
      "HALMILTON",
      "LAKKA",
      "LAKKA JUNCTION",
      "SAN DRIVE",
      "SAIDU LANE",
      "PONTO DRIVE",
      "KOGBO",
      "KABBA DRIVE",
      "K BANGS DRIVE",
      "DEEN SANKOH DRIVE",
      "BAH LANE",
      "DESMOND LANE",
      "HAMILTON VILLAGE JUNCTION ROAD",
    ],
  },
  {
    zone: "ZONE 2",
    regions: [
      "LAKKA",
      "OGOO FARM",
      "ANGOLA",
      "ADONKIA",
      "COLLLEGE ROAD",
      "METCHEM JUCTION",
      "FEMI TURNER",
      "FUNKIA",
      "BAH JUNCTION",
      "GODRICH",
      "BATTLION",
      "JUBA BARRACK",
      "JUBA",
      "LUMLEY",
      "MALAMA",
      "BABADORIE",
      "REGENT ROAD LUMLEY",
      "BANGA FARM",
      "COCKLE BAY",
      "JUBA HILL",
      "TARAWALLEY DRIVE",
      "FOFANAH DRIVE",
      "YUMKELLA ROAD",
      "CEMETERY ROAD",
      "KOIVAYA AMARA DRIVE",
      "GODERICH ROAD",
    ],
  },
  {
    zone: "ZONE 3",
    regions: [
      "TOKEH",
      "YORK",
      "KENT",
      "BUREH",
      "NO.2",
      "JOHN OBEY",
      "BLACLK JOHNSON",
      "TOMBO",
      "RUSSEL",
      "WATERLOO",
    ],
  },
  {
    zone: "ZONE 4",
    regions: [
      "LUMLEY BEACH ROAD",
      "BEACH ROAD",
      "WILKINSON ROAD",
      "FAMILY KINGDOM",
      "COCKERY",
      "BIG HOUSE",
      "INDIA TEMPLE",
      "SMART FARM JUNCTION",
      "COLLAGIATE JUNCTION",
      "DISTNY DRIVE",
      "FIELDER LANE",
      "SCAN DRIVE",
      "WHITE POLE",
      "ABERDEEN ROAD",
      "SIR SAMUEL LEWIS ROAD",
      "MUDGE FARM",
      "GRAMMER SCHOOL JUNTION",
      "ABERDEEN",
      "ABERDEEN VILLAGE",
      "SOSO VILLAGE",
      "MURRAY TOWN",
      "CONGO CROSS",
      "KING STREET CONGO TOWN",
      "WATER STREET",
      "GIRL SCHOOL",
      "TECHINAL SCHOOL",
      "ASCENSION TOWN",
      "SYKE STREET",
      "ADLELAIDE STREET",
      "BROOKFIELD",
      "TEGBEH TOWN",
      "YUYIE BUILDING",
      "SAVAGE BRIDGE",
      "ST JOHN",
    ],
  },
  {
    zone: "ZONE 5",
    regions: [
      "SANDER STREET",
      "EDWARD STREET",
      "BROOK STREET",
      "CONGO MARKRT",
      "CIRCULAR ROAD",
      "PADAMBA ROAD",
      "WATERLOO STREET",
      "BATHURST STREET",
      "WELLINGTON STREET",
      "POULTNEY STREET",
      "LIVERERPOOL STREET",
      "LAMINA SANKOH STREET",
      "LIGHTFOOOT BOSTON STREET",
      "CHARLOTTE STEERT",
      "RAWDON STREET",
      "WILBERFORCE STREET",
      "PZ",
      "GODRICH STREET",
      "MOUNTAIN CUT",
      "NEW ENGLAND FIELD",
      "DWARZACK",
      "MODEL NEW ROAD",
      "MODEL OLD ROAD",
      "MOUNT OREL",
      "KISSY ROAD",
      "SAVAGE SQURE",
      "SANI ABACHA",
      "EASTERN POLICE",
    ],
  },
  {
    zone: "ZONE 6",
    regions: [
      "UP-GUN",
      "CLINE TOWN",
      "FERRY JUNCTION",
      "PORTEE",
      "KISSY BROOK",
      "WELLINGTON",
      "GRASS FIELD",
      "THUNDER HILL",
      "SHELL",
      "KALABA TOWN",
      "ALLEN TOWN",
      "JUI",
      "GRAFTON",
      "HASTING",
      "PMB JUNCTION",
      "SHELL KISSY",
      "CONGO WATER",
      "ROKEL JUNCTION",
      "KISSY DOCKYARD",
      "JENNER WRIGHT",
      "BARRACKS OLD ROAD",
      "JUI ROAD",
      "BAIMBU DRIVE",
      "FOMBA DRIVE",
      "LEIGH ROAD",
      "SYER AVENUE",
      "BACK STREET",
      "JUI STATION ROAD",
    ],
  },
  {
    zone: "ZONE 7",
    regions: [
      "HASTINGS",
      "KOSSO TOWN",
      "DEVIL HOLE",
      "YAMS FARM",
      "ROKEL",
      "BANGA FARM",
      "SUSSEX JUNCTION",
      "TOMBO JUNCTION",
      "WATERLOO CLOCK TOWER",
      "55 JUNCTION",
      "WATERLOO CENTRAL JUNCTION",
      "CHINA HOSPITAL JUNCTION",
      "GRAFTON JUNCTION",
      "GRAFTON REGENT ROAD JUNCTION",
      "MAMBO JUNCTION",
      "FOUR MILE JUNCTION",
      "WATERLOO HIGHWAY",
      "CHURCH STREET",
      "KING STREET",
      "FREY STREET",
      "ROGBANGBA ROAD",
      "FOUR MILE ACCESS ROAD",
    ],
  },
  {
    zone: "ZONE 8",
    regions: [
      "LUMLEY",
      "LUMLEY ROAD",
      "SPUR ROAD",
      "FREETOWN ROAD",
      "WILBERFORCE",
      "WILBERFORCE VILLAGE",
      "SIGNALL HILL",
      "SPURLOOP",
      "HILL CUT",
      "HILL STATION",
      "IMATT",
      "LEICESTER",
      "GLOUCESTER",
      "BATHURST VILLAGE",
      "BATHURST JUNCTION",
      "BATHURST MAIN ROAD",
    ],
  },
  {
    zone: "ZONE 9",
    regions: [
      "IMATT JUNCTION",
      "REGENT",
      "HINGA ROAD",
      "BALLAY LANE",
      "TURAY DRIVE",
      "HULKET LANE",
      "ROBERT STREET",
      "THOMAS STREET",
      "MASCOM DRIVE",
      "YAYAH LANE",
      "CYPRUS ROAD",
      "SESAY LANE",
      "RENNER DRIVE",
      "KEBBI DRIVE",
      "JUI",
      "KOSSOH TOWN",
      "BASSA TOWN",
      "FREETOWN TEACHERS COLLEGE JUNCTION",
    ],
  },
  {
    zone: "ZONE 10",
    regions: [
      "AIR -FERRY ROAD",
      "ERNEST BAI KOROMA",
      "PETER CONTEH STREET",
      "KAMARA STREET",
      "MAHERAH",
      "TINTAFOR",
      "KALLON STREET",
      "MODU STREET",
      "MASUBA ROAD",
      "MUBUREH ROAD",
      "KOYA ROAD",
      "TAGRIN",
      "MASOLIA",
      "SAWKTAR",
      "KASONGAHA",
      "TULUN",
      "YONGORO",
    ],
  },
  {
    zone: "ZONE 11",
    regions: [
      "MOKERA",
      "PETIFUL",
      "GBONKOPIL",
      "MASORIE",
      "MAGBAFTH",
      "SONGO",
      "ROGBERE",
      "MILE 36",
      "MAKANEH",
      "ROWAL",
      "MAKOSE",
      "MAYONGA",
      "MABEKE",
      "MATEI",
      "YEMA",
      "MAKOYA",
    ],
  },
  {
    zone: "ZONE 12",
    regions: [
      "MAGBURAKA ROAD",
      "KAABALA HIGHWAY",
      "MAKENI FREETOWN HIGH WAY",
      "TEKO ROAD",
      "WUSUM ROAD",
      "CAMPBELL STREET",
      "AZZOLINI HIGHWAY",
      "STATION ROAD",
      "NEW LONDON ROAD",
      "MASONS ROAD",
      "VILLAGE",
      "HANGA ROADE",
      "WUSUM VILLAGE",
      "MASONGBO VILLAGE",
      "MAKARI VILLAGE",
      "KAGBERE VILLAGE",
      "KAMABAI VILLAGE",
      "KAMAKWIE VILLAGE",
      "MANGE VILLAGE",
      "MATHINKA VILLAGE",
      "ROSINT VILLAGE",
      "BINKOLO",
      "BATKANU",
      "GBENDEMBU",
      "MAKARIE",
      "MABONTO",
    ],
  },
  {
    zone: "ZONE 13",
    regions: [
      "DAMBLA ROAD",
      "KISSY ROAD",
      "MISSION ROAD",
      "TIKONKO",
      "NJALA ROAD",
      "HOSPITAL ROAD",
      "MATTRU",
      "JUBILLE",
      "BAI BUREH ROAD",
      "GOVERNMENT ROAD",
      "NJALA",
      "KORIBONDO",
      "SUMBUYA",
      "MOGERE",
      "BAOMA",
      "BUMPE",
      "GBOYAMA",
      "NGELEHUN",
      "JIMMI",
      "TELU",
      "KAKUA",
      "BADJIA",
      "BAGBO",
      "SELENGA",
    ],
  },
  {
    zone: "ZONE 14",
    regions: [
      "MAXWELL KHOBE STREET",
      "DAMA ROAD",
      "BLAMA",
      "DEMBAY STREET",
      "MAIN STREET",
      "CIRCULAR ROAD",
      "KINGSWAYS STREET",
      "ABDULAI STREET",
      "ABDUL SANDY STREET",
      "BAKISSA STREET",
      "BARWOH STREET",
      "BOCKRIEBAY STREET",
      "BRIMA KARGBO STREET",
      "ENSA STREET",
      "COOPER LANE",
      "DAUD SANDY STREET",
      "FATIMEH STREET",
      "FASEI STRREET",
      "FELLIE STREET",
      "FOYAH STREET",
      "TONGO",
      "KANGA",
      "ISLAMIC STREET",
      "ISATU STREET",
      "KAMANDA STREET",
    ],
  },
  {
    zone: "ZONE 15",
    regions: [
      "YENGEMA ROAD",
      "TOMBODU ROAD",
      "SEWAFE ROAD",
      "JIAMA NIMiKORO",
      "MOTEMA ROAD",
      "KANGAMA ROAD",
      "KENEMA HIGHWAY",
      "GOVERNMENT HOSPITAL ROAD",
      "KOIDU MAIN STREET",
      "SAFADU ROAD",
      "STATION ROAD",
      "TANKORO",
      "KAMIENDOU",
      "KAINKORDU",
      "SIAMA",
      "PEYIMA",
      "FOINDU",
      "TEFEYA",
      "TOMENDEH",
      "YARDU",
      "SOA",
      "TOLI",
      "MAFINDOR",
    ],
  },
  {
    zone: "Administrative Provinces",
    regions: [
      "Eastern Province",
      "Northern Province",
      "North West Province",
      "Southern Province",
      "Western Area",
    ],
  },
  {
    zone: "Other",
    regions: ["Other"],
  },
]

// Deduplicated array of all valid region names
export const ALL_LOCATION_REGIONS: string[] = Array.from(
  new Set(LOCATION_ZONES.flatMap((z) => z.regions))
)

// Specific zone names (ZONE 1 to ZONE 15)
export const SPECIFIC_ZONE_NAMES: string[] = LOCATION_ZONES
  .filter((z) => z.zone.startsWith("ZONE"))
  .map((z) => z.zone)

// All specific location regions in ZONE 1 - 15 sorted by length descending
export const SPECIFIC_LOCATION_REGIONS: string[] = Array.from(
  new Set(
    LOCATION_ZONES.filter((z) => z.zone.startsWith("ZONE")).flatMap((z) => z.regions)
  )
).sort((a, b) => b.length - a.length)

// Administrative Province regions
export const PROVINCE_REGIONS: string[] = [
  "Eastern Province",
  "Northern Province",
  "North West Province",
  "Southern Province",
  "Western Area",
]

// Map from region name (uppercase/trimmed) to Zone name
const REGION_TO_ZONE_MAP: Record<string, string> = {}
LOCATION_ZONES.forEach((z) => {
  z.regions.forEach((r) => {
    REGION_TO_ZONE_MAP[r.trim().toUpperCase()] = z.zone
  })
})

export function getZoneForRegion(regionName?: string | null): string {
  if (!regionName) return "Other"
  const clean = regionName.trim().toUpperCase()
  return REGION_TO_ZONE_MAP[clean] || "Other"
}
